{
  "name": "catch-express-error",
  "version": "0.1.6",
  "description": "It is a Node.js package for handling and catching errors in Express.js applications.",
  "main": "dist/index.cjs",
  "author": "nextyfine-dev",
  "license": "MIT",
  "exports": {
    ".": {
      "require": "./dist/index.cjs",
      "import": "./source/index.mjs"
    }
  },
  "scripts": {
    "build": "yarn run build_mjs && yarn run build_cjs && yarn run convert_cjs && yarn run convert_mjs",
    "build_cjs": "npx tsc -p tsconfig.cjs.json",
    "build_mjs": "npx tsc -p tsconfig.json",
    "convert_cjs": "chfe -f dist -ce js -ne cjs",
    "convert_mjs": "chfe -f source -ce js -ne mjs"
  },
  "devDependencies": {
    "@types/express": "^4.17.17",
    "@types/node": "^20.4.2",
    "chfe": "^0.1.4",
    "express": "^4.18.2",
    "tslib": "^2.6.0",
    "typescript": "^5.1.6",
    "winston": "^3.10.0"
  },
  "types": "./source/index.d.ts",
  "keywords": [
    "error handler",
    "error handling middleware",
    "express",
    "middleware",
    "validation",
    "error handling",
    "async",
    "typescript",
    "request",
    "response",
    "utility",
    "utilities",
    "validation middleware",
    "express middleware",
    "async error handling",
    "request validation",
    "response handling",
    "error management",
    "error wrapper",
    "catch errors",
    "express errors",
    "request errors",
    "response errors",
    "request validation middleware",
    "response error handling",
    "express error handler"
  ],
  "repository": {
    "type": "git",
    "url": "git+https://github.com/nextyfine-dev/catch-express-errors.git"
  },
  "bugs": {
    "url": "https://github.com/nextyfine-dev/catch-express-errors/issues"
  },
  "homepage": "https://github.com/nextyfine-dev/catch-express-errors#readme"
}